name: Build LaTeX document

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build_latex:
    name: XeLaTeX build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: LaTeX compilation
        uses: dante-ev/latex-action@2026-A
        with:
          root_file: cv.tex
          compiler: xelatex
          args: -interaction=nonstopmode -file-line-error

      - name: Save PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: cv.pdf

  create_release:
    name: Github Release
    needs: build_latex
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up tag
        run: |
            NEW_TAG=$(date +'%Y.%m.%d')
            LAST_TAG=$(git tag --sort=creatordate | tr '\n' ' ' | sed -e "s/ $NEW_TAG //" | tr ' ' '\n | tail -1')
            {
              echo "RELEASE_TAG=$NEW_TAG"
              echo "RELEASE_NAME=$(date +'%Y/%m/%d') - Curriculum Vitae"
              echo "RELEASE_PDF=$(date +'%Y')-Marcel-Olaru.pdf"
              echo "RELEASE_BODY<<BODY_EOF"
              git log --pretty='format:- %s' $LAST_TAG..HEAD
              echo ""
              echo "BODY_EOF"
            } >> "$GITHUB_ENV"

      - name: Retrieve PDF
        uses: actions/download-artifact@v4
        with:
          name: pdf

      - name: Rename PDF for release
        run: mv cv.pdf "$RELEASE_PDF"

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          body: ${{ env.RELEASE_BODY }}
          files: ${{ env.RELEASE_PDF }}
